"""add processed webhooks table

Revision ID: 1cab4e991bf8
Revises: b3adf963e560
Create Date: 2026-08-25 10:55:45.363442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cab4e991bf8'
down_revision: Union[str, Sequence[str], None] = 'b3adf963e560'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_webhooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_webhooks_event_id'), 'processed_webhooks', ['event_id'], unique=True)
    op.create_index(op.f('ix_processed_webhooks_id'), 'processed_webhooks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processed_webhooks_id'), table_name='processed_webhooks')
    op.drop_index(op.f('ix_processed_webhooks_event_id'), table_name='processed_webhooks')
    op.drop_table('processed_webhooks')
    # ### end Alembic commands ###
